# Image for building the application .jar
FROM maven:3.9.4-eclipse-temurin-17 AS builder

WORKDIR /build

COPY pom.xml .
COPY src/main ./src/main

RUN mvn clean package -DskipTests

# Image for running the application
FROM openjdk:17-jdk-alpine

WORKDIR /profiles_service

COPY --from=builder /build/target/*.jar app.jar

ARG PROFILES_SERVICE_PORT
ARG PROFILES_DB_SERVICE_NAME
ARG PROFILES_DB_SERVICE_PORT
ARG PROFILES_DB_USER
ARG PROFILES_DB_PASSWORD
ARG PROFILES_DB_NAME

ENV PROFILES_SERVICE_PORT=${PROFILES_SERVICE_PORT}
ENV PROFILES_DB_SERVICE_NAME=${PROFILES_DB_SERVICE_NAME}
ENV PROFILES_DB_SERVICE_PORT=${PROFILES_DB_SERVICE_PORT}
ENV PROFILES_DB_USER=${PROFILES_DB_USER}
ENV PROFILES_DB_PASSWORD=${PROFILES_DB_PASSWORD}
ENV PROFILES_DB_NAME=${PROFILES_DB_NAME}

EXPOSE ${PROFILES_SERVICE_PORT}

CMD [ "java", "-jar", "app.jar" ]